"""The v2 data model: a pose library, and sequences of blocks with markers.

This replaces the Routine model (an ordered list of waypoints with actions
hanging off them). The rename is load-bearing, as it was last time. A Sequence
is built from *blocks* — holds at a library pose, transitions between them —
and the actions live in *markers* pinned to a time position inside their parent
block. Actions moved off the block list on purpose: in a block model, moving a
station means multi-selecting its actions too, and missing one detaches the
shutter from the pose — a whole round of empty frames. A marker inside its
parent block cannot be detached from it. Same technique as the ActionContext
that carries no arm handle: make the wrong thing unreachable, not forbidden.

The shapes here mirror ``frontend/src/types.ts`` and the mock
(``frontend/mock/``) field for field — the React UI was built against the mock,
and this backend implements that contract. When the two disagree, the mock
wins.

The workflow stays linear: arrive, hold, trigger, move on. Markers fire in
order, a failed marker aborts the run, and a wait marker suspends it. No
conditions, no branches — adding an action *kind* is a new provider, and that
is the extension point that matters.
"""

from __future__ import annotations

import math
import time
import uuid
from typing import Annotated, Literal, Union

from pydantic import BaseModel, Field, field_validator

#: Bumped when a stored document's shape changes incompatibly. v1 was the
#: waypoint-list Routine; it has been retired without migration.
SCHEMA_VERSION = 2

#: Defaults for an auto-generated transition: slow and smooth beats fast.
#: Mirror DEFAULT_TRANSITION_S / DEFAULT_EASING in frontend/src/timeline/model.ts.
DEFAULT_TRANSITION_S = 2.0
DEFAULT_EASING = "ease_in_out"

#: The built-in marker kind. Anything else names an action provider.
WAIT_KIND = "wait"

Easing = Literal["linear", "ease_in", "ease_out", "ease_in_out"]


def _new_id() -> str:
    return uuid.uuid4().hex[:12]


class Pose(BaseModel):
    """A named arm pose in the library. Hold blocks link to it by id.

    Joint *names* and joint *limits* are deliberately not validated here, same
    as the old Waypoint: limits come from the URDF, this model only guarantees
    the shape is sane.
    """

    id: str = Field(default_factory=_new_id)
    name: str = Field(min_length=1, max_length=200)
    #: Joint angles in radians, keyed by hardware joint name.
    joints: dict[str, float]
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)

    @field_validator("joints")
    @classmethod
    def _joints_must_be_finite_and_present(cls, v: dict[str, float]) -> dict[str, float]:
        if not v:
            raise ValueError("a pose needs at least one joint angle")
        bad = sorted(n for n, q in v.items() if not math.isfinite(q))
        if bad:
            raise ValueError(f"joint angles must be finite; got NaN/inf for {bad}")
        return v

    def touch(self, now: float | None = None) -> None:
        self.updated_at = time.time() if now is None else now


class EventMarker(BaseModel):
    """An action pinned inside its parent block, at a time position inside it.

    Inside a hold ``at`` is a second offset (0..duration_s); inside a
    transition it is a proportion (0..1) — splitting a transition to say
    "midway" would invent a pose nobody taught.
    """

    id: str = Field(default_factory=_new_id)
    #: "wait" is built in; anything else is a provider id (e.g. "shutter").
    kind: str = Field(min_length=1, max_length=64)
    #: Provider params (shutter: count/interval_s/focus_first); wait has none.
    params: dict = Field(default_factory=dict)
    at: float = Field(ge=0)
    #: Estimated execution time in seconds, for the translucent span display.
    #: Instant triggers ≈ 0.3; a wait marker is open-ended and carries 0.
    estimate_s: float = Field(default=0.3, ge=0)


class HoldBlock(BaseModel):
    """Stay at a library pose for ``duration_s``. The station."""

    type: Literal["hold"] = "hold"
    id: str = Field(default_factory=_new_id)
    #: Link, not a copy: the joints live in the library pose.
    pose_id: str = Field(min_length=1)
    duration_s: float = Field(default=3.0, ge=0, le=600)
    markers: list[EventMarker] = Field(default_factory=list)


class TransitionBlock(BaseModel):
    """Get to the next station's pose over ``duration_s``.

    Generated by normalization, never edited into existence by hand: two
    different poses adjacent means the arm must physically get there, and that
    is not a setting.
    """

    type: Literal["transition"] = "transition"
    id: str = Field(default_factory=_new_id)
    duration_s: float = Field(default=DEFAULT_TRANSITION_S, gt=0, le=600)
    easing: Easing = DEFAULT_EASING
    markers: list[EventMarker] = Field(default_factory=list)


#: Discriminated on ``type``, so a stored sequence round-trips back to the
#: right class. Adding a block kind means adding it here.
Block = Annotated[
    Union[HoldBlock, TransitionBlock], Field(discriminator="type")
]


class Sequence(BaseModel):
    """An ordered list of blocks — one shoot."""

    schema_version: int = SCHEMA_VERSION
    id: str = Field(default_factory=_new_id)
    name: str = Field(min_length=1, max_length=200)
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)
    blocks: list[Block] = Field(default_factory=list)

    def touch(self, now: float | None = None) -> None:
        self.updated_at = time.time() if now is None else now


class SequenceSummary(BaseModel):
    """Enough to render the library list without loading every block.

    ``duration_s`` is the plan-ruler length: the sum of *commanded* durations.
    Markers add nothing — their durations are estimates and a wait marker is
    open-ended, so the UI always labels this number 预估.
    """

    id: str
    name: str
    updated_at: float
    #: Number of hold blocks (stations).
    station_count: int
    duration_s: float

    @classmethod
    def of(cls, sequence: Sequence) -> "SequenceSummary":
        from .normalize import sequence_duration

        return cls(
            id=sequence.id,
            name=sequence.name,
            updated_at=sequence.updated_at,
            station_count=sum(1 for b in sequence.blocks if isinstance(b, HoldBlock)),
            duration_s=sequence_duration(sequence.blocks),
        )


class SeqTemplate(BaseModel):
    """A structural recipe: blocks with each hold's pose_id replaced by a slot
    placeholder ("slot:1".."slot:N"). No joint angles — a template's value is
    the structure, and angles taught in one studio are wrong in another.
    """

    id: str = Field(default_factory=_new_id)
    name: str = Field(min_length=1, max_length=200)
    created_at: float = Field(default_factory=time.time)
    station_count: int = Field(ge=1)
    recipe: list[Block] = Field(default_factory=list)
